### ISSUE TITLE
Issue with grpc in gverse in the new version

### ISSUE THREAD

**Issue by ahmedbrandver** [gverse/gverse#10]
I am getting the following error while running my application, I have updated to the new version of ***gverse***:

![gverse error](https://user-images.githubusercontent.com/52484387/65233202-e3786a00-daeb-11e9-8198-944cfb5a2031.jpg)

**Comment by zakmandhro** [comment]
Looks like grpc compatibility issue. I'll upgrade grpc module and confirm.
